# Generated by Django 6.0.3 on 2026-03-07 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('block', 'Block Level'), ('district', 'District Level'), ('state', 'State Level'), ('final', 'Final Approval')], max_length=20, unique=True)),
                ('hours_to_escalate', models.IntegerField(default=24)),
                ('escalate_to', models.CharField(choices=[('block', 'Block Level'), ('district', 'District Level'), ('state', 'State Level'), ('final', 'Final Approval')], max_length=20)),
                ('notify_via_email', models.BooleanField(default=True)),
                ('notify_via_sms', models.BooleanField(default=True)),
                ('notify_via_whatsapp', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Escalation Rule',
                'verbose_name_plural': 'Escalation Rules',
                'db_table': 'escalation_rules',
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_level', models.CharField(choices=[('block', 'Block Level'), ('district', 'District Level'), ('state', 'State Level'), ('final', 'Final Approval')], default='block', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='members.member')),
            ],
            options={
                'verbose_name': 'Approval Workflow',
                'verbose_name_plural': 'Approval Workflows',
                'db_table': 'approval_workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('block', 'Block Level'), ('district', 'District Level'), ('state', 'State Level'), ('final', 'Final Approval')], max_length=20)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('request_info', 'Request More Info'), ('escalate', 'Escalate')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalworkflow')),
            ],
            options={
                'verbose_name': 'Approval Action',
                'verbose_name_plural': 'Approval Actions',
                'db_table': 'approval_actions',
                'ordering': ['created_at'],
            },
        ),
    ]
