# Generated by Django 5.2.10 on 2026-04-22 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalworkflow",
            name="level_entered_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="approvalworkflow",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escalationrule",
            name="hours_to_remind",
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name="escalationrule",
            name="escalate_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("block", "Block Level"),
                    ("district", "District Level"),
                    ("state", "State Level"),
                    ("final", "Final Approval"),
                ],
                max_length=20,
            ),
        ),
    ]
