# Generated by Django 6.0.3 on 2026-03-07 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('area_type', models.CharField(choices=[('block', 'Block'), ('district', 'District'), ('state', 'State')], max_length=20)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='members.geographicarea')),
            ],
            options={
                'verbose_name': 'Geographic Area',
                'verbose_name_plural': 'Geographic Areas',
                'db_table': 'geographic_areas',
                'ordering': ['area_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('caste', models.CharField(blank=True, max_length=50, null=True)),
                ('social_category', models.CharField(blank=True, choices=[('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('CC', 'Converted Christians from SC'), ('OBC', 'Other Backward Class'), ('O', 'Others')], max_length=3, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('educational_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_doing_business', models.BooleanField(default=False)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('constitution', models.CharField(blank=True, choices=[('PROP', 'Proprietorship'), ('PART', 'Partnership'), ('PVT', 'Private Limited'), ('PUB', 'Public Limited'), ('OPC', 'One Person Company'), ('LLP', 'Limited Liability Partnership'), ('TRUST', 'Trust'), ('SOC', 'Society')], max_length=10, null=True)),
                ('business_type', models.CharField(blank=True, choices=[('M', 'Manufacturing'), ('S', 'Service'), ('T', 'Trader'), ('D', 'Dealer')], max_length=1, null=True)),
                ('business_activities', models.TextField(blank=True, null=True)),
                ('business_commencement_year', models.IntegerField(blank=True, null=True)),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
                ('msme_registered', models.BooleanField(default=False)),
                ('msme_number', models.CharField(blank=True, max_length=50, null=True)),
                ('nsic_registered', models.BooleanField(default=False)),
                ('nsic_number', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_registered', models.BooleanField(default=False)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ie_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('udyam_number', models.CharField(blank=True, max_length=50, null=True)),
                ('has_filed_itr', models.BooleanField(default=False)),
                ('itr_filing_years', models.IntegerField(blank=True, null=True)),
                ('turnover_range', models.CharField(blank=True, choices=[('<40L', '< 40 Lakhs'), ('<1CR', '40 Lakhs - 1 Crore'), ('<5CR', '1 - 5 Crore'), ('<50CR', '5 - 50 Crore'), ('<250CR', '50 - 250 Crore'), ('<500CR', '250 - 500 Crore'), ('>1000CR', '> 1000 Crore')], max_length=10, null=True)),
                ('member_of_other_chambers', models.BooleanField(default=False)),
                ('other_chamber_details', models.TextField(blank=True, null=True)),
                ('profile_completion_percentage', models.IntegerField(default=0)),
                ('profile_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, limit_choices_to={'area_type': 'block'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_members', to='members.geographicarea')),
                ('district', models.ForeignKey(blank=True, limit_choices_to={'area_type': 'district'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_members', to='members.geographicarea')),
                ('state', models.ForeignKey(blank=True, limit_choices_to={'area_type': 'state'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_members', to='members.geographicarea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentSchemeBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=255)),
                ('benefit_details', models.TextField()),
                ('availed_year', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_benefits', to='members.member')),
            ],
            options={
                'verbose_name': 'Government Scheme Benefit',
                'verbose_name_plural': 'Government Scheme Benefits',
                'db_table': 'government_scheme_benefits',
            },
        ),
        migrations.CreateModel(
            name='SisterConcern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('constitution', models.CharField(choices=[('PROP', 'Proprietorship'), ('PART', 'Partnership'), ('PVT', 'Private Limited'), ('PUB', 'Public Limited'), ('OPC', 'One Person Company'), ('LLP', 'Limited Liability Partnership'), ('TRUST', 'Trust'), ('SOC', 'Society')], max_length=10)),
                ('business_type', models.CharField(choices=[('M', 'Manufacturing'), ('S', 'Service'), ('T', 'Trader'), ('D', 'Dealer')], max_length=1)),
                ('turnover_range', models.CharField(choices=[('<40L', '< 40 Lakhs'), ('<1CR', '40 Lakhs - 1 Crore'), ('<5CR', '1 - 5 Crore'), ('<50CR', '5 - 50 Crore'), ('<250CR', '50 - 250 Crore'), ('<500CR', '250 - 500 Crore'), ('>1000CR', '> 1000 Crore')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sister_concerns', to='members.member')),
            ],
            options={
                'verbose_name': 'Sister Concern',
                'verbose_name_plural': 'Sister Concerns',
                'db_table': 'sister_concerns',
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['user'], name='members_user_id_7f6dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['block', 'district', 'state'], name='members_block_i_2ede6f_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['social_category'], name='members_social__d75f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['is_doing_business'], name='members_is_doin_9f5ab5_idx'),
        ),
    ]
