# Generated by Django 5.2.10 on 2026-04-22 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_approved_at_member_is_approved_memberdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="fpo_annual_turnover",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="fpo_ceo_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="fpo_ceo_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="fpo_commodity",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="fpo_crop_types",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="fpo_farmer_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="fpo_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="fpo_registration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="fpo_registration_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="fpo_total_land_area_acres",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="member_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("shg", "Self Help Group (SHG)"),
                    ("fpo", "Farmer Producer Organisation (FPO)"),
                ],
                default="individual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="shg_bank_account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="shg_bank_linked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="shg_bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="shg_federation_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="shg_formation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="shg_member_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="shg_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="shg_promoting_institution",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="shg_registration_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="memberdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("aadhaar", "Aadhaar Card"),
                    ("pan", "PAN Card"),
                    ("gst", "GST Certificate"),
                    ("udyam", "Udyam Registration Certificate"),
                    ("business_reg", "Business Registration"),
                    ("itr", "Income Tax Return"),
                    ("shg_reg", "SHG Registration Certificate"),
                    ("shg_bank", "SHG Bank Passbook"),
                    ("shg_members", "SHG Member List"),
                    ("fpo_reg", "FPO Registration Certificate"),
                    ("fpo_bylaw", "FPO By-Laws"),
                    ("fpo_shareholders", "FPO Shareholder List"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["member_type"], name="members_member__ccd43d_idx"
            ),
        ),
    ]
